Fix 'PageData.LanguageBranch' is obsolete: 'Use ILocalizable.Language…
episerver/alloy-mvc-template pull request #7
Opened 2018-03-07 12:41 UTC by kmukku

… instead' with the html element on _Root.cshtml

2018-03-20 05:08 UTC, barteksekula requested changes

2018-03-20 05:08 UTC, barteksekula commented on src/Alloy.Mvc.Template/Models/Pages/SitePageData.cs
> -    public abstract class SitePageData : PageData, ICustomCssInContentArea
PageData does already implement ILocalizable, please remove that change and I will accept your PR

2018-03-20 13:03 UTC, kmukku reviewed
True. For some reason I did miss that at the time. Now I can't approve my own PR.

2018-06-15 11:31 UTC, seriema commented
@kmukku Then we'll close the PR :) If you disagree let us know.

2018-06-15 11:31 UTC, closed without merging